### ISSUE TITLE
Crash when opening YT

### ISSUE THREAD

**Issue by lasic01** [feelfreelinux/WykopMobilny#111]
I get FC every time when I want to expand YT window. ver 0.8.0

In 0.8.1.5 there is an error initializing player.

**Comment by msnowak** [comment]
Same here. 0.9.0.0. Set yt full screen or rotate screen when yt is on.

**Comment by feelfreelinux** [comment]
Fixed in https://github.com/feelfreelinux/WykopMobilny/commit/7f8ff820b9af1420c7e8d5f62502b0b936842316

**Comment by feelfreelinux** [comment]
0.9.3 will be released soon
