### ISSUE TITLE
Nothing happens when trying to save image.

### ISSUE THREAD

**Issue by michaldrabik** [feelfreelinux/WykopMobilny#130]
Clicking "Zapisz obraz" does nothing at all. Image is not being saved.

Device: OnePlus 5 Android 8.1

Attaching video:
https://i.imgur.com/bzYZi24.mp4

**Comment by MiXereg** [comment]
Have you had added storage permissions?

**Comment by michaldrabik** [comment]
That did solve the case actually. Totally forgot about this possibility.

However I should probably just be asked for this permission when neccessary for API >= 23.

**Comment by MiXereg** [comment]
New images implementation was added in the last update, so it can be bugged.

**Comment by feelfreelinux** [comment]
Reopening as dialog should show up

**Comment by michaldrabik** [comment]
> Reopening as dialog should show up
What should happen if the user checked "Never ask again" before?

**Comment by rnickson** [comment]
>What should happen if the user checked "Never ask again" before?

I've seen a lot of apps opening app permission settings in this case

**Comment by feelfreelinux** [comment]
Fixed in last update
