### ISSUE TITLE
Tags grouping

### ISSUE THREAD

**Issue by oscyp** [feelfreelinux/WykopMobilny#133]
Support of grouping observed tags will be nice (with counter). That solution was provided on Windows Phone by tylkoMirko app and community approved it very well.

Couldn't help because of Kotlin.

**Comment by feelfreelinux** [comment]
Do you have a screenshot of this feature? Got few requests about this, but I don't really get how this would work.

And Kotlin is really begginer's friendly, just message me on discord if you want to help

**Comment by feelfreelinux** [comment]
Currently working on it.

**Comment by feelfreelinux** [comment]
Done https://github.com/feelfreelinux/WykopMobilny/commit/50cbdd8e0d887c4c92ba8a724d7c49c6148e9946
