### ISSUE TITLE
Can't vote on comments in main section of Wykop

### ISSUE THREAD

**Issue by kokosowy** [feelfreelinux/WykopMobilny#186]
![Screenshot_20200315-065750_Wykop_Mobilny](https://user-images.githubusercontent.com/7746083/76696392-43129500-668b-11ea-9f9c-b2f1af490fe2.png)

Rather major issue.

**Comment by unweek** [comment]
Hey, unfortunately the mistake is on the side of Wykop. The official app has the same problem.
