### ISSUE TITLE
Brakuje dark mode

### ISSUE THREAD

**Issue by kampoz** [feelfreelinux/WykopMobilny#190]
j.w.

**Comment by selfisekai** [comment]
chyba twojej starej brakuje, ustawienia włącz

**Comment by unweek** [comment]
Dark mode jest dostępny w ustawieniach aplikacji

**Comment by takidelfin** [comment]
Przecież to nawet wykopki znajdują, łatwiej się nie da już. Nawet pewnie mimoza wstydliwa by się nauczyła obsługiwać to listkami

**Comment by kvdrrrrr** [comment]
czemu nie wykurwisz na codeberg jak github jest żydowski co?

**Comment by kvdrrrrr** [comment]
a masz fiutka ? ? ?

**Comment by kvdrrrrr** [comment]
masz juz sperme

**Comment by kvdrrrrr** [comment]
@selfisekai Jesteś piękny. On. Laury (jego) wygląd jest piękny.

**Comment by kvdrrrrr** [comment]
@selfisekai To urodzony programista.

**Comment by ohme1** [comment]
> 
> 
> @selfisekai To urodzony programista.

Programistczynia. Zwracaj uwagę na zaimki albo siedź cicho.

**Comment by kvdrrrrr** [comment]
Aha. Przepraszam Cię Laurze.

**Comment by unweek** [comment]
Nie macie innego zajęcia o tej porze, poza próbowaniem zdenerwowania Laury?

**Comment by kvdrrrrr** [comment]
sory juz nie bede!

**Comment by ohme1** [comment]
W sumie masz rację. Sorry, Laura (on)!

**Comment by ptrcnull** [comment]
ale szambo wybiło

**Comment by kvdrrrrr** [comment]
jenyyy ile groźny levvakuw webdevowych z penisami, pora wykurwiac xD

**Comment by ptrcnull** [comment]
XD marny troll, spadaj na kara czy skądkolwiek przylazłeś

**Comment by kvdrrrrr** [comment]
kupa/kupy :DD

**Comment by takidelfin** [comment]
P-prawak na GitHubie? D:
To jednak faktycznie wśród nich są tacy co umieją into programowańsko.

Przykro mi, ale GitHub popiera _lewackie ideologie_ :)

**Comment by feelfreelinux** [comment]
Z wiadomych względów issue zamykam. Błagam, zachowujmy się jak ludzie.

**Comment by kampoz** [comment]
Dark mode powinien sie uruchamiac, gdy w Androidzie jest wlaczony tryb nocny, a sie nie wlacza.
Powinny byc 2 xmle ze stylami dla mode dark i light, nie wiem czy są, ale po zachowaniu apki zakladam, ze nie ma. 
Nie znasz sie to nie zabieraj glosu gimbo @selfisekai

**Comment by ptrcnull** [comment]
W takim razie popraw tytuł/treść issue na "Tryb nocny nie uruchamia się automatycznie zgodnie z trybem nocnym Androida", bo tryb nocny w aplikacji jest, co wszyscy ci wypomnieli.

**Comment by unweek** [comment]
Aplikacja była tworzona, gdy Android jeszcze nie miał tej funkcji. Obecnie nikt nad nią nie pracuje, więc nie zostanie to dodane. W hybrydowej aplikacji być może to dodamy, ale w tej chwili nie wiadomo.

**Comment by Kroguc** [comment]
@kampoz kurde, muszę się zgodzić z gimbusami, mają rację. Do czego to doszło 🤔

**Comment by kampoz** [comment]
OK, niech wam bedzie, w takim razie trzeba zalozyc nowy issue :)

**Comment by takidelfin** [comment]
Ale faktycznie tu szambo wylało xD
