### ISSUE TITLE
Night mode does not work correctly

### ISSUE THREAD

**Issue by jakubparysz** [feelfreelinux/WykopMobilny#36]
# Steps to reproduce:
1. Open settings
2. Check night mode field
3. See night mode in settings
4. Go to main page
```diff 
- 5. See main page is not night mode 
```
# Expected:
```diff 
+ See main page in night mode
```

**Comment by m-karas** [comment]
Force closing and opening the app makes is done. You can just tell user, that it needs restart for working and close him the app.
