### ISSUE TITLE
Ucięta treść komentarzy 

### ISSUE THREAD

**Issue by mdczaplicki** [feelfreelinux/WykopMobilny#42]
![screenshot_2017-11-08-12-41-07-779_io github feelfreelinux wykopmobilny](https://user-images.githubusercontent.com/9108586/32547364-51ea9d6e-c482-11e7-9641-99bce9a6f84e.png)

Apka ucina treść komentarzy. Czasem pół czasem jedna albo nawet dwie literki znikają poza obszarem.

**Comment by feelfreelinux** [comment]
Błąd poprawiony
