### ISSUE TITLE
Zmniejszyć rozmiar nicków

### ISSUE THREAD

**Issue by mdczaplicki** [feelfreelinux/WykopMobilny#45]
![screenshot_2017-11-09-20-40-58-359_io github feelfreelinux wykopmobilny](https://user-images.githubusercontent.com/9108586/32626065-7e13ec44-c58e-11e7-9a1d-84cda910b6f6.png)

Nicki w komentarzach są trochę za duże. Pomijam już fakt, że wchodzą pod plusa - bo to można rozwiązać np ucinając zbyt długiego stringa. Po prostu optycznie te nicki są za duże.

**Comment by feelfreelinux** [comment]
Poprawione
