### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by mdczaplicki** [feelfreelinux/WykopMobilny#47]
![screenshot_2017-11-14-11-07-33-471_com miui bugreport](https://user-images.githubusercontent.com/9108586/32774344-4749e744-c92c-11e7-9956-1900c41c4b77.png)
Bylem w gorących 6h i pojawił się ten wpis:
https://www.wykop.pl/wpis/28004755/wlasnie-sie-dowiedzialem-ze-ta-szmata-mnie-zdradzi/
Kliknąłem spoiler I pokazał się a następnie go zamknąłem i chciałem wejść w ten wpis i wyskoczył ten exception. 

Jeszcze kilka razy mi się ten błąd pojawił. Żeby go odtworzyć należy znaleźć wpis z obrazkiem i:
otworzyć obrazek
cofnąć
otworzyć
cofnąć
otworzyć
cofnąć
...
prędzej czy później wywali ten błąd.

**Comment by feelfreelinux** [comment]
Fixed in https://github.com/feelfreelinux/WykopMobilny/commit/5dc84ca6cb716f8fc048b1fcf2796182af845c6b
