### ISSUE TITLE
Kliknięcie w pustą przestrzeń obok tagu przekierowuje do tagu zamiast do posta

### ISSUE THREAD

**Issue by bholota** [feelfreelinux/WykopMobilny#48]
Jak odtworzyć problem: 
1. Wpis musi mieć przynajmniej jeden tag, najlepiej w nowej linii, po nim nie ma już nic.
2. Wystarczy próbować otworzyć wpis klikając w pustą przestrzeń na prawo od tagu.

No i lipa, otworzyliśmy wpisy w tagu. Podobny problem występuje z linkami.

**Comment by feelfreelinux** [comment]
Fixed in https://github.com/feelfreelinux/WykopMobilny/commit/5dc84ca6cb716f8fc048b1fcf2796182af845c6b
