### ISSUE TITLE
Nieczytelny obraz po pobraniu (wysoka rozdzielczość)

### ISSUE THREAD

**Issue by mtomana** [feelfreelinux/WykopMobilny#54]
Przykładowy wpis: https://www.wykop.pl/wpis/28219739/
Przy zdjęciu można by to przeżyć, ale przy obrazku gdzie jest tekst - brak możliwości przeczytania :(

Podgląd w WykopMobilny:
![Screenshot 2017-11-29 13 06 38](https://user-images.githubusercontent.com/12294378/33374440-822851bc-d506-11e7-9a40-03bae7f011bf.png)

Podgląd w aplikacji oficjalnej:
![Screenshot 2017-11-29 13 04 44](https://user-images.githubusercontent.com/12294378/33374423-717fb04e-d506-11e7-9f09-6d7f0a15f2a1.png)

**Comment by mtomana** [comment]
Przy okazji - w oficjalnej aplikacji, powiększanie jest dostępne tylko do pewnego momentu (jak w załączonym screenie). W praktyce obrazek ma 1366px szerokości, spokojnie można by go dalej powiększać.

**Comment by m-karas** [comment]
Obstawiam
Link z końcówką rodzaju ,q_n_.jpg lub ,w_n_.png.
Po usunięciu tego elementu powinna się pobierać pełna rozdzielczość.

**Comment by feelfreelinux** [comment]
Poprawiłem ten błąd dawno temu, zapomniałem zamknąć issue
