### ISSUE TITLE
Exception po powrocie

### ISSUE THREAD

**Issue by mdczaplicki** [feelfreelinux/WykopMobilny#56]
Zminimalizowałem aplikację będąc w konkretnym wpisie. Po godzinie otworzyłem aplikację i byłem cały czas w tym wpisie. Kliknąłem wstecz żeby wrócić do mikrobloga i wywaliło taki błąd:
![screenshot_2017-12-02-11-57-36-991_com miui bugreport](https://user-images.githubusercontent.com/9108586/33514672-4bea9156-d758-11e7-8e08-631733601870.png)

**Comment by feelfreelinux** [comment]
Poprawiłem to ostatnio
