### ISSUE TITLE
Build - jak wygenerować klucz?

### ISSUE THREAD

**Issue by gjedeer** [feelfreelinux/WykopMobilny#68]
Musiałem zaznaczyć złe opcje przy generowaniu klucza API (apka budowana samodzielnie), bo dostaję taki błąd:

![kaenitghtt2uv-gx328sgq](https://user-images.githubusercontent.com/315648/35275291-8b7af3aa-003f-11e8-9069-18de4e21c7bc.jpg)

Jak wygenerować poprawny klucz?

**Comment by luk1337** [comment]
Jako śmiertelnik nie dostaniesz klucza APIv2, sam osobiście ukradłem sobie klucz z release .apk.

**Comment by gjedeer** [comment]
Fuck. Kombinujemy jak to wrzucić na F-Droid, a z kradzionym kluczem nie wypada :|

**Comment by rnickson** [comment]
@feelfreelinux swój klucz dostał i z niego korzystamy, więc nie do końca kradziony powiedzmy ( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)
Możesz skorzystać z tego z release .apk ([dekompiler online](https://javadecompilers.com/apk) lub jakikolwiek inny -> `io/github/feelfreelinux/wykopmobilny/BuildConfig.java`) albo z tego - `aNd401dAPp`, sekretu do niego nie ma z niewiadomych przyczyn, ogólnie żądania z tym kluczem idą niepodpisane.

**Comment by feelfreelinux** [comment]
@gjedeer Hej, sam też próbuje ogarnąć jak wrzucić apkę na F-Droid, niestety nie mogę jej wrzucić bo korzystamy z jednej biblioteki Google - bez tego `android-job` coś nawala, musiałbym obejrzeć czy da się to czymś zastąpić.

**Comment by gjedeer** [comment]
@feelfreelinux z biblioteką ci nie pomogę, natomiast jak będziesz miał jakiekolwiek problemy z F-Droidem albo po prostu nie będzie ci się chciało, pisz.

Używasz tego do sprawdzania co nowego na Wykopie i pokazywania powiadomień, dobrze ze źródeł rozumiem?

**Comment by gjedeer** [comment]
Hmm, a może taki fork? https://github.com/mat-dr/android-job

**Comment by gjedeer** [comment]
Zbudowałem z tym forkiem (dzięki za tipa z kluczami @rnickson ) i działa. Zaraz zrobię PR, a tego ticketa zamykam.
