### ISSUE TITLE
Pokazuj komentarze pod wpisem 

### ISSUE THREAD

**Issue by dkuku** [feelfreelinux/WykopMobilny#85]
Przydalaby sie opcja pokazywania kilku najlepszych komentarzy pod wpisem i znaleziskiem, nie trzebaby wtedy wchodzic w kazde aby sprawdzic co sie tam dzieje

**Comment by manhunto** [comment]
tak to! troszkę mi tego brakuje

**Comment by Kroguc** [comment]
Uh, dwa lata. Gdy tylko skończymy hybrydę (xD), a Maciej lub Michał dodadzą to do API, bankowo dodamy.
