### ISSUE TITLE
Implement Drawer

### ISSUE THREAD

**Issue by feelfreelinux** [feelfreelinux/WykopMobilny#9]
Application should implement navigation drawer in all activities. 
We should probably move from activities into fragments.

**Comment by noiserr** [comment]
Maybe BottomNavigation instead of drawer?

**Comment by feelfreelinux** [comment]
@noiserr [I made a poll ](https://www.wykop.pl/wpis/25557953/)

**Comment by feelfreelinux** [comment]
This was done in lastest commits
