### ISSUE TITLE
New content providing services not supported

### ISSUE THREAD

**Issue by rnickson** [feelfreelinux/WykopMobilny#98]
Wykop added new supported content providing services on YouTube - as announced here: https://wykop.pl/wpis/30155471 - streamable.com, coub.com, twitch.tv. This app now downloads miniatures, but it doesn't show any information about service or even it's a video.

**Comment by feelfreelinux** [comment]
@Kroguc

**Comment by feelfreelinux** [comment]
Done

**Comment by rnickson** [comment]
@feelfreelinux well, it's good, but it's missing SoundCloud.com
here's an example: https://wykop.pl/wpis/25594887
